name: octadesk_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Sub projects
  octadesk_conversation:
    path: ../octadesk_conversation
  octadesk_services:
    path: ../octadesk_services
  octadesk_core:
    path: ../octadesk_core

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  camera: ^0.10.0+4
  camera_windows: ^0.2.1+2
  collection: ^1.16.0
  go_router: ^5.1.1
  provider: ^6.0.4
  url_launcher: ^6.1.6
  connectivity_plus: ^3.0.2
  package_info_plus: ^3.0.1
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1
  transparent_image: ^2.0.0
  intl: ^0.17.0
  flutter_slidable: ^2.0.0
  scrollable_positioned_list: ^0.3.5
  audioplayers: ^1.1.1
  path_provider: ^2.0.11
  styled_text: ^6.0.0
  rich_text_controller: ^1.4.0
  rxdart: ^0.27.5
  dio: ^4.0.6
  bitsdojo_window: ^0.1.5
  file_picker: ^5.2.2
  path: ^1.8.2
  record: ^4.4.3
  permission_handler: ^10.2.0
  get_it: ^7.2.0
  easy_mask: ^2.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  msix: ^3.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/app_icon/default.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "lib/assets/app_icon/windows.png"
    icon_size: 256 # min:48, max:256, default: 48

msix_config:
  display_name: Octadesk
  publisher_display_name: Octadesk
  identity_name: Octadesk.OctadeskDesktop
  publisher: CN=F0A2E49B-46E6-4E4A-A0F0-0E2F8A2CFEB9
  msix_version: 1.0.0.0
  logo_path: lib/assets/app_icon/windows.png
  store: true
  

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/badges/
    - lib/assets/illustrations/
    - lib/assets/flags/
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/poppins/Poppins-Regular.ttf
        - asset: lib/assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
